version: '3.8'

services:
  signaling-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: co-planet-signaling-server
    ports:
      - "7589:3000"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
    restart: unless-stopped